//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelOfFuelColumn
    {
        public int ID { get; set; }
        public int FuelID { get; set; }
        public int ColumnID { get; set; }
    
        public virtual Fuel Fuel { get; set; }
        public virtual FuelColumn FuelColumn { get; set; }
    }
}
